daemon on;

worker_processes auto;

pid /run/nginx-port80.pid;

events {
    worker_connections 1024;
}

http {
    access_log /var/log/nginx-port80/access.log;
    error_log /var/log/nginx-port80/error.log;

    server {
        listen 80;

        location / {
            return 200 "Hello from nginx-port80 on port 80\n";
        }
    }
}
