daemon on;

worker_processes auto;

pid /run/nginx-port8080.pid;

events {
    worker_connections 1024;
}

http {
    access_log /var/log/nginx-port8080/access.log;
    error_log /var/log/nginx-port8080/error.log;

    server {
        listen 8080;

        location / {
            return 200 "Hello from nginx-port8080 on port 8080\n";
        }
    }
}
